### ISSUE TITLE
Augmentation spec rotation

### ISSUE THREAD

**Issue by SteveEbey73742** [kaminaris/MaxDps-Evoker#5]
What do you need, to create a augmentation rotation.  I would be willing to test one, or tell me what tools I would need, to try to make one. I have some ilmited lua coding experience.

**Comment by doadin** [comment]
I have pushed out a update and while aug is now add especially with how aug works I can't guarantee it will perform like other dps rotations. If anyone has any fixes/updates/better knowledge on how to improve aug im open to any ideas and I am in the discord.

**Comment by SteveEbey73742** [comment]
I will attempt to test and report back. I am off work this week, pending my mother in laws funeral service. My wife is having a hard time.
